prompt --application/shared_components/user_interface/templates/page/gkasto
begin
--   Manifest
--     TEMPLATE: GKASTO
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>1829437844690909
,p_default_application_id=>102
,p_default_id_offset=>0
,p_default_owner=>'XXPOKASTO'
);
wwv_flow_api.create_template(
 p_id=>wwv_flow_api.id(1968417659227077)
,p_theme_id=>42
,p_name=>'GKasto'
,p_internal_name=>'GKASTO'
,p_is_popup=>false
,p_header_template=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">',
'<html lang="es">',
'<head>',
'    <meta charset="UTF-8">',
'    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'    <meta http-equiv="X-UA-Compatible" content="ie=edge">',
'    <title>Grupo Kasto</title>',
unistr('      <meta name="description" content="Grupo Kasto es un grupo empresarial mexicano con m\00E1s de 75 a\00F1os de experiencia en el sector agroindustrial, incluyendo molinos de trigo, producci\00F3n de granos, servicios log\00EDsticos, productos de consumo y m\00E1s.">'),
unistr('      <meta name="keywords" content="Grupo Kasto, agroindustria, harinas, molinos, granos, log\00EDstica, pecuaria, invernaderos, panader\00EDa, productos de consumo, M\00E9xico">'),
'      <meta name="author" content="Grupo Kasto">',
'',
'      <!-- Open Graph / Facebook -->',
'      <meta property="og:title" content="Grupo Kasto - Excelencia Agroindustrial Mexicana">',
unistr('      <meta property="og:description" content="Conoce las divisiones de Grupo Kasto: Granos, Molinos de trigo, Pecuaria, Servicios, Invernaderos, Panader\00EDa, Productos de consumo y m\00E1s.">'),
'      <meta property="og:url" content="https://www.grupokasto.com">',
'      <meta property="og:type" content="website">',
'',
'      <!-- Twitter -->',
'      <meta name="twitter:card" content="summary_large_image">',
'      <meta name="twitter:title" content="Grupo Kasto">',
unistr('      <meta name="twitter:description" content="L\00EDder en agroindustria en M\00E9xico con m\00E1s de 75 a\00F1os de experiencia en m\00FAltiples sectores productivos.">'),
'      <meta name="twitter:image" content="https://www.grupokasto.com/ords/r/grupokasto/files/static/v1/images/logo.png">',
'   ',
'    <link rel="apple-touch-icon" sizes="180x180" href="##APP_IMAGES#Loader_2.png">',
'    <link rel="icon" type="image/png" sizes="32x32" href="#APP_IMAGES#logobal-1.png">',
'    <link rel="icon" type="image/png" sizes="16x16" href="#APP_IMAGES#Loader_2.png">',
'    <link rel="manifest" href="#APP_IMAGES#Loader_2.png">',
'    ',
'',
'    <!-- Fonts-->',
'     <link',
'        href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"',
'        rel="stylesheet">',
'    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap" rel="stylesheet">',
'    <link href=''https://fonts.googleapis.com/css?family=Barlow Condensed'' rel=''stylesheet''>',
'                ',
'    <!-- Css-->',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/animate.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/bootstrap.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/owl.carousel.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/owl.theme.default.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/magnific-popup.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/fontawesome-all.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/swiper.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/bootstrap-select.min.css">',
'    <link rel="stylesheet" href="https://molinosgrupokasto.com/PortalGK/assets/css/lang-buttons.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/jquery.mCustomScrollbar.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/bootstrap-datepicker.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/vegas.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/nouislider.min.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/nouislider.pips.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/jquery.bxslider.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/agrikol_iconl.css">',
'    <!-- Template styles -->',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/style.css">',
'    <link rel="stylesheet" href="#APP_IMAGES#assets/css/responsive.css">',
'',
'     <style type="text/css">',
'        h3 {',
'            font-size: 40px;',
'        }',
'        html, body {',
'            width: 100%;',
'            max-width: 100%;',
'        }',
'        .page-wrapper {',
'            width: 100%;',
'            max-width: 100%;',
'            margin-left: auto;',
'            margin-right: auto;',
'        }',
'        .site-header__header-one-wrap .container,',
'        .main-nav__header-one .container {',
'            margin-left: auto !important;',
'            margin-right: auto !important;',
'            max-width: 1200px;',
'        }',
'        nav.gk-main-nav.header-navigation {',
'            display: block;',
'        }',
'        @media (min-width: 1200px) {',
'            .site-header__header-one-wrap .main-nav__header-one .header-navigation .container,',
'            .site-header__header-one-wrap nav.gk-main-nav .container {',
'                display: flex !important;',
'                -webkit-box-pack: center !important;',
'                justify-content: center !important;',
'                -webkit-box-align: center !important;',
'                align-items: center !important;',
'                flex-wrap: nowrap;',
'            }',
'            .site-header__header-one-wrap .main-nav__header-one .main-nav__left {',
'                display: none !important;',
'                width: 0 !important;',
'                max-width: 0 !important;',
'                margin: 0 !important;',
'                padding: 0 !important;',
'                overflow: hidden !important;',
'            }',
'            .site-header__header-one-wrap .main-nav__header-one .main-nav__main-navigation {',
'                display: flex !important;',
'                -webkit-box-flex: 1;',
'                flex: 1 1 auto !important;',
'                width: 100% !important;',
'                max-width: 100% !important;',
'                margin: 0 !important;',
'                padding: 0 !important;',
'                -webkit-box-pack: center;',
'                justify-content: center;',
'            }',
'            .site-header__header-one-wrap .main-nav__header-one .main-nav__navigation-box {',
'                -webkit-box-pack: center !important;',
'                justify-content: center !important;',
'                flex-wrap: wrap;',
'                margin-left: auto !important;',
'                margin-right: auto !important;',
'            }',
'        }',
'    </style>',
'   <!-- Google tag (gtag.js) -->',
'   <script async src="https://www.googletagmanager.com/gtag/js?id=G-241ZSMZBXR"></script>',
'   <script>',
'     window.dataLayer = window.dataLayer || [];',
'     function gtag(){dataLayer.push(arguments);}',
'     gtag(''js'', new Date());',
'',
'     gtag(''config'', ''G-241ZSMZBXR'');',
'   </script>',
'   ',
'   <script type="application/ld+json">',
'      {',
'        "@context": "https://schema.org",',
'        "@type": "Organization",',
'        "name": "Grupo Kasto",',
'        "url": "https://www.grupokasto.com",',
'        "logo": "https://www.grupokasto.com/ords/r/grupokasto/files/static/v1/images/logo.png",',
'        "sameAs": [',
'          "https://www.facebook.com/grupokasto",',
'          "https://www.linkedin.com/company/grupokasto",',
'          "https://www.instagram.com/grupokasto/"',
'        ],',
unistr('        "description": "Grupo empresarial mexicano l\00EDder en agroindustria con m\00E1s de 75 a\00F1os de experiencia en m\00FAltiples sectores productivos.",'),
'        "address": {',
'          "@type": "PostalAddress",',
'          "addressCountry": "MX"',
'        }',
'      }',
'   </script>',
'',
'   ',
'    #HEAD#',
'</head>',
'#FORM_OPEN#',
'<body>',
'',
'    <div class="preloader">',
'        <img src="#APP_IMAGES#Loader_2.png" class="preloader__image" alt="">',
'    </div><!-- /.preloader -->',
'    <div class="page-wrapper">',
'        <div class="site-header__header-one-wrap">',
'            <div class="topbar-one">',
'                <div class="topbar_bg" style="background-image: url(#APP_IMAGES#assets/images/shapes/header-bg.png)"></div>',
'                <div class="container" style="    margin-top: 15px;">',
'                    <div class="topbar-one__left">',
'                        <a href="mailto:contacto@grupokasto.com"><span class="icon-message"></span>contacto@grupokasto.com</a>',
'                        <a href="tel:352-526-1939"><span class="icon-phone-call"></span>(352) 526 1939</a>     ',
'                    </div>',
'                    <div class="topbar-one__middle">',
'                        <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:1:&SESSION." class="main-nav__logo">',
'                            <img src="#APP_IMAGES#assets/images/logo-gk_2.png" class="main-logo" alt="Awesome Image" />',
'                        </a>  ',
'                    </div>',
'          ',
'                    <div class="topbar-one__right">',
'                        <div class="topbar-one__social">',
'                            <a href="https://mx.linkedin.com/company/grupokasto" target="_BLANK" ><i class="fab fa-linkedin"></i></a>',
'                            <a href="https://www.facebook.com/grupokasto" target="_BLANK"><i class="fab fa-facebook-square"></i></a>',
'                            <a href="https://instagram.com/grupokasto?igshid=1aft09hsxo30m" target="_BLANK"><i class="fab fa-instagram"></i></a>',
'                            ',
'                            <a id="top-lang-button-es">',
'                                <i>',
'                                    <!--<img src="https://molinosgrupokasto.com/PortalGK/assets/images/template/icon/BtnsIcons/ES_v5_gris.png">-->',
'                                </i>',
'                            </a>',
'                            ',
'                            <a id="top-lang-button-en">',
'                               <i>',
'                                    <!--<img src="https://molinosgrupokasto.com/PortalGK/assets/images/template/icon/BtnsIcons/EN_v5_gris.png">-->',
'                                </i>',
'                            </a>',
'                            <!--<a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>',
'                            <a href="https://instagram.com/"><i class="fab fa-instagram"></i></a>',
'                            <a href="https://dribbble.com/"><i class="fab fa-dribbble"></i></a>-->',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'',
'            <header class="main-nav__header-one">',
unistr('                <nav class="gk-main-nav header-navigation stricky" role="navigation" aria-label="Men\00FA principal">'),
'                    <div class="container clearfix">',
'                        <!-- Brand and toggle get grouped for better mobile display -->',
'                        <div class="main-nav__left">',
'                            ',
'                            <a href="#" class="side-menu__toggler">',
'                          <i class="fa fa-bars"></i>',
'                            </a>',
'                        </div>',
'                        <div class="main-nav__main-navigation">',
'                            <ul class="main-nav__navigation-box">',
'                                <li class="dropdown current">',
'                                    <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:1:&SESSION.">Inicio</a>',
'                                </li>',
'                                <li class="dropdown">',
'                                    <a href="   #">Nosotros</a>',
'                                    <ul>                                             ',
'                                                <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:3:&SESSION.">Historia</a></li>',
unistr('                                                <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:16:&SESSION.">Filosof\00EDa</a></li>'),
'                                                <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:17:&SESSION.">Certificaciones</a></li>',
unistr('                                                <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:5:&SESSION.">Galer\00EDa</a></li>'),
'                                            </ul><!-- /.sub-menu -->',
'                                </li>',
'                                <li class="dropdown">',
'                                    <a href="#">Divisiones</a>',
'                                    <ul>',
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:7:&SESSION.">Divisi\00F3n Granos</a></li>'),
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:8:&SESSION.">Divisi\00F3n Molinos de trigo</a></li>'),
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:9:&SESSION.">Divisi\00F3n Pecuaria</a></li>'),
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:13:&SESSION.">Divisi\00F3n Servicios</a></li>'),
'                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:10:&SESSION.">Invernaderos</a></li>',
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:4:&SESSION.">Panader\00EDa y bistr\00F3</a></li>'),
'                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:14:&SESSION.">Productos de consumo</a></li>',
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:15:&SESSION.">Promotora de inversi\00F3n</a></li>'),
'',
'                                    </ul><!-- /.sub-menu -->',
'                                </li>',
'                                <li class="dropdown">',
'                                    <a href="#">Servicios</a>',
'                                    <ul>',
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:18:&SESSION.">Log\00EDstica y originaci\00F3n</a></li>'),
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:19:&SESSION.">Comercializaci\00F3n</a></li>'),
unistr('                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:20:&SESSION.">Asesor\00EDa y consultor\00EDa</a></li>'),
'                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:21:&SESSION.">Desarrollo de proyectos</a></li>',
'                                    </ul>',
'                                </li>',
'                                <li class="dropdown">',
'                                    <a href="#">Noticias</a>',
'                                    <ul>',
'                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:11:&SESSION.">Noticias</a></li>',
'                                        <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:29:&SESSION.">Noticias detalladas</a></li>',
'',
'                                    </ul>',
'                                </li>',
'                               <li class="dropdown">',
'                                    <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:45:&SESSION.">Sostenibilidad</a>',
'                                </li>',
'                                    <li class="dropdown">',
'                                    <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:2:&SESSION.">Contacto</a>',
'                                </li>',
'                                     ',
'                            </ul>',
'                        </div><!-- /.navbar-collapse -->                      ',
'                    </div>',
'                </nav>',
'            </header>',
'        </div>'))
,p_box=>'#BODY#'
,p_footer_template=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<footer class="site-footer">',
'    <div class="site-footer_farm_image">',
'        <img src="#APP_IMAGES#pie.png" alt="Farm Image" />',
'    </div>',
'    <div class="container">',
'        <div class="row no-gutters">',
'            <div class="col-xl-4 col-lg-4 col-md-6">',
'                <div class="footer-widget__column footer-widget__about wow fadeInUp" data-wow-delay="100ms">',
'                    <div class="footer-widget__title">',
'                        <h3>Grupo Kasto</h3>',
'                    </div>',
'                    <div class="footer-widget_about_text">',
'                        <p>',
unistr('                            \00A1Queremos servirte mejor!. Para cualquier inquietud o duda, te'),
unistr('                            invitamos a que nos env\00EDes un correo electr\00F3nico. Hacemos de tu'),
'                            conocimiento nuestros:',
'                        </p>',
'                    </div>',
'                    <div class="footer-widget_contact">',
'                        <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:6:&SESSION.">Avisos de Privacidad de las',
'                            Empresas</a>',
'                    </div>',
'                </div>',
'            </div>',
'            <div class="col-xl-2 col-lg-2 col-md-6">',
'                <div class="footer-widget__column footer-widget__link wow fadeInUp" data-wow-delay="200ms">',
'                    <div class="footer-widget__title">',
'                        <h3>Explora</h3>',
'                    </div>',
'                    <ul class="footer-widget__links-list list-unstyled">',
'                        <li>',
'                            <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:1:&SESSION.">Inicio</a>',
'                        </li>',
'                        <li>',
'                            <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:3:&SESSION.">Nosotros</a>',
'                        </li>',
'                        <li>',
'                            <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:7:&SESSION.">Divisiones</a>',
'                        </li>',
'                        <li><a href="#">Servicios</a></li>',
'                        <li><a href="#">Noticias</a></li>',
'                        <li>',
'                            <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:2:&SESSION.">Contacto</a>',
'                        </li>',
'                    </ul>',
'                </div>',
'            </div>',
'            <div class="col-xl-3 col-lg-3 col-md-6">',
'                <div class="footer-widget__column footer-widget__news wow fadeInUp" data-wow-delay="300ms">',
'                    <div class="footer-widget__title">',
'                        <h3>Noticias</h3>',
'                    </div>',
'                    <ul class="footer-widget__news list-unstyled">',
'                        <li>',
'                            <div class="footer-widget__news_image">',
'                                <img src="#APP_IMAGES#news_22_img_header.png" alt="" />',
'                            </div>',
'                            <div class="footer-widget__news_text">',
'                                <p>',
'                                    <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:44:&SESSION.">Colaboradores',
'                                        participan en jornada de voluntariado para el cuidado de los bosques</a>',
'                                </p>',
'                            </div>',
'                            <div class="footer-widget__news_date_box">',
'                                <p>07 Nov 2025</p>',
'                            </div>',
'                        </li>',
'',
'                        <li>',
'                            <div class="footer-widget__news_image">',
'                                <img src="#APP_IMAGES#news_21_img_header.png" alt="" />',
'                            </div>',
'                            <div class="footer-widget__news_text">',
'                                <p>',
'                                    <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:43:&SESSION.">Celebrando con',
unistr('                                        \00E9xito la Semana de la Seguridad 2025</a>'),
'                                </p>',
'                            </div>',
'                            <div class="footer-widget__news_date_box">',
'                                <p>02 May 2025</p>',
'                            </div>',
'                        </li>',
'',
'                        <!-- <li>',
'              <div class="footer-widget__news_image">',
'                <img src="#APP_IMAGES#news_20_img_header.png" alt="" />',
'              </div>',
'              <div class="footer-widget__news_text">',
'                <p>',
'                  <a',
'                    href="https://www.grupokasto.com/ords/PDB1/f?p=102:42:&SESSION."',
'                    >Simulacro Nacional en Molino Planta Central: Reforzando',
unistr('                    nuestra cultura de prevenci\00F3n</a'),
'                  >',
'                </p>',
'              </div>',
'              <div class="footer-widget__news_date_box">',
'                <p>29 Abr 2025</p>',
'              </div>',
'            </li> -->',
'                    </ul>',
'                </div>',
'            </div>',
'            <div class="col-xl-3 col-lg-3 col-md-6">',
'                <div class="footer-widget__column footer-widget__contact wow fadeInUp" data-wow-delay="400ms">',
'                    <div class="footer-widget__title">',
'                        <h3>Contacto</h3>',
'                    </div>',
'                    <div class="footer-widget_contact">',
'                        <p>Av. Padre Hidalgo #600<br />Santa Ana Pco, Gto. 36910</p>',
'                        <a href="mailto:contacto@grupokasto.com">contacto@grupokasto.com</a><br />',
'                        <a href="tel:352-526-1939">352 526 1939</a>',
'                        <div class="site-footer__social">',
'                            <a href="https://mx.linkedin.com/company/grupokasto" target="_BLANK"><i',
'                                    class="fab fa-linkedin"></i></a>',
'                            <a href="https://www.facebook.com/grupokastomolinos/" target="_BLANK"><i',
'                                    class="fab fa-facebook-square"></i></a>',
'                            <a href="https://instagram.com/grupokasto?igshid=1aft09hsxo30m" target="_BLANK"><i',
'                                    class="fab fa-instagram"></i></a>',
'                            <a id="bottom-lang-button-es">',
'                                <i>',
'                                    <!--<img src="https://molinosgrupokasto.com/PortalGK/assets/images/template/icon/BtnsIcons/ES_v5_verde.png">-->',
'                                </i>',
'                            </a>',
'                            <a id="bottom-lang-button-en">',
'                                <i>',
'                                    <!--<img src="https://molinosgrupokasto.com/PortalGK/assets/images/template/icon/BtnsIcons/EN_v5_verde.png">-->',
'                                </i>',
'                            </a>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </div>',
'    </div>',
'</footer>',
'',
'',
'<div class="site-footer_bottom">',
'',
'    <div class="container">',
'        <!--div class="site-footer_bottom_copyright">',
unistr('                <p style="color:#878986"><a href="http://grupokasto.com/" class="footer-widget_contact" style="color: #c5c9c4;">Grupo Kasto </a>\00A9 2020 Derechos Reservados</p>'),
'                </div>-->',
'',
'        <div class="site-footer_bottom_copyright" style="padding:4px;">',
'            <span class="footer-apex">',
unistr('                <a href="https://www.grupokasto.com/ords/PDB1/f?p=102:1:&SESSION.">Grupo Kasto</a> \00A9 <span'),
'                    id="currentYear"></span> Derechos Reservados',
'            </span>',
'        </div>',
'',
'        <script>',
unistr('            // Obtiene el a\00F1o actual y lo inserta en el span con id currentYear'),
'            document.getElementById(''currentYear'').textContent = new Date().getFullYear()',
'        </script>',
'',
'',
'        <div class="site-footer_bottom_copyright">',
'',
'        </div>',
'        <div class="site-footer_bottom_copyright" style="padding:4px;">',
'            <span class="footer-apex">Built with',
'                <span class="fa fa-heart"></span> using <a href="https://apex.oracle.com"> Oracle APEX</a></span>',
'        </div>',
'    </div>',
'</div>',
'',
'',
'',
'',
'</div><!-- /.page-wrapper -->',
'<a href="#" data-target="html" class="scroll-to-target scroll-to-top"><i class="fa fa-angle-up"></i></a>',
'<div class="side-menu__block">',
'    <div class="side-menu__block-overlay custom-cursor__overlay">',
'        <div class="cursor"></div>',
'        <div class="cursor-follower"></div>',
'    </div><!-- /.side-menu__block-overlay -->',
'    <div class="side-menu__block-inner ">',
'        <div class="side-menu__top justify-content-end">',
'            <a href="#" class="side-menu__toggler side-menu__close-btn"><img',
'                    src="#APP_IMAGES#assets/images/shapes/close-1-1.png" alt=""></a>',
'        </div><!-- /.side-menu__top -->',
'',
'        <nav class="mobile-nav__container">',
'            <!-- content is loading via js -->',
'        </nav>',
'',
'        <div class="side-menu__sep"></div><!-- /.side-menu__sep -->',
'',
'        <div class="side-menu__content">',
'            <p><a href="mailto:contacto@grupokasto.com">contacto@grupokasto.com</a> <br> <a href="tel:333-647-8792">352',
'                    526 1939</a></p>',
'            <div class="side-menu__social">',
'                <a href="https://mx.linkedin.com/company/grupokasto" target="_BLANK"><i class="fab fa-linkedin"></i></a>',
'                <a href="https://www.facebook.com/grupokastomolinos/" target="_BLANK"><i',
'                        class="fab fa-facebook-square"></i></a>',
'                <a href="https://instagram.com/grupokasto?igshid=1aft09hsxo30m" target="_BLANK"><i',
'                        class="fab fa-instagram"></i></a>',
'                <a id="side-lang-button-es"><i><img',
'                            src="https://molinosgrupokasto.com/PortalGK/assets/images/template/icon/BtnsIcons/ES_v5_side.png"></i></a>',
'                <a id="side-lang-button-en"><i><img',
'                            src="https://molinosgrupokasto.com/PortalGK/assets/images/template/icon/BtnsIcons/EN_v5_side.png"></i></a>',
'            </div>',
'        </div>',
'    </div>',
'</div>',
'',
'',
'<div class="search-popup">',
'    <div class="search-popup__overlay custom-cursor__overlay">',
'        <div class="cursor"></div>',
'        <div class="cursor-follower"></div>',
'    </div><!-- /.search-popup__overlay -->',
'    <div class="search-popup__inner">',
'        <form action="#" class="search-popup__form">',
'            <input type="text" name="search" placeholder="Type here to Search....">',
'            <button type="submit"><i class="fa fa-search"></i></button>',
'        </form>',
'    </div>',
'</div>',
'',
'',
'',
'<script src="#APP_IMAGES#assets/js/jquery.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/bootstrap.bundle.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/owl.carousel.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/waypoints.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/jquery.counterup.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/TweenMax.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/wow.js"></script>',
'<script src="#APP_IMAGES#assets/js/jquery.magnific-popup.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/jquery.ajaxchimp.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/swiper.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/typed-2.0.11.js"></script>',
'<script src="#APP_IMAGES#assets/js/vegas.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/jquery.validate.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/bootstrap-select.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/countdown.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/jquery.mCustomScrollbar.concat.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/bootstrap-datepicker.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/nouislider.min.js"></script>',
'<script src="#APP_IMAGES#assets/js/isotope.js"></script>',
'<script src="#APP_IMAGES#assets/js/appear.js"></script>',
'<script src="#APP_IMAGES#assets/js/jquery.bxslider.min.js"></script>',
'',
'',
'<!-- template scripts -->',
'<script src="#APP_IMAGES#assets/js/theme.js"></script>',
'',
'#FORM_CLOSE#',
'#APEX_JAVASCRIPT#',
'#THEME_JAVASCRIPT#',
'#TEMPLATE_JAVASCRIPT#',
'#APPLICATION_JAVASCRIPT#',
'#PAGE_JAVASCRIPT#',
'#GENERATED_JAVASCRIPT#',
'</body>',
'',
'</html>'))
,p_theme_class_id=>0
,p_grid_type=>'TABLE'
,p_grid_always_use_max_columns=>false
,p_grid_has_column_span=>true
,p_grid_always_emit=>true
,p_grid_emit_empty_leading_cols=>true
,p_grid_emit_empty_trail_cols=>false
,p_translate_this_template=>'Y'
);
wwv_flow_api.component_end;
end;
/
