prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/assets_css_style_css.sql
@@application/shared_components/files/assets_css_jquery_bxslider_css.sql
@@application/shared_components/files/assets_css_jquery_mcustomscrollbar_min_css.sql
@@application/shared_components/files/assets_css_jquery_ui_css.sql
@@application/shared_components/files/assets_css_magnific_popup_css.sql
@@application/shared_components/files/assets_css_nouislider_min_css.sql
@@application/shared_components/files/assets_css_nouislider_pips_css.sql
@@application/shared_components/files/assets_css_owl_carousel_min_css.sql
@@application/shared_components/files/assets_css_owl_theme_default_min_css.sql
@@application/shared_components/files/assets_css_responsive_css.sql
@@application/shared_components/files/assets_css_swiper_min_css.sql
@@application/shared_components/files/assets_css_tripo_icons_css.sql
@@application/shared_components/files/assets_css_vegas_min_css.sql
@@application/shared_components/files/assets_images_filosofia_jpg.sql
@@application/shared_components/files/style_css.sql
@@application/shared_components/files/assets_images_invernaderos_jpg.sql
@@application/shared_components/files/assets_js_apmeum_min_js_descarga.sql
@@application/shared_components/files/assets_js_appear_js_descarga.sql
@@application/shared_components/files/assets_js_bootstrap_bundle_min_js_descarga.sql
@@application/shared_components/files/assets_js_bootstrap_datepicker_min_js_descarga.sql
@@application/shared_components/files/assets_js_bootstrap_select_min_js_descarga.sql
@@application/shared_components/files/assets_js_countdown_min_js_descarga.sql
@@application/shared_components/files/assets_js_isotope_js_descarga.sql
@@application/shared_components/files/assets_js_jquery_ajaxchimp_min_js_descarga.sql
@@application/shared_components/files/assets_js_jquery_bxslider_min_js_descarga.sql
@@application/shared_components/files/assets_js_jquery_counterup_min_js_descarga.sql
@@application/shared_components/files/assets_js_jquery_magnific_popup_min_js_descarga.sql
@@application/shared_components/files/assets_js_jquery_mcustomscrollbar_concat_min_js_descarga.sql
@@application/shared_components/files/assets_js_jquery_min_js_descarga.sql
@@application/shared_components/files/assets_js_jquery_validate_min_js_descarga.sql
@@application/shared_components/files/assets_js_nouislider_min_js_descarga.sql
@@application/shared_components/files/assets_js_owl_carousel_min_js_descarga.sql
@@application/shared_components/files/assets_js_swiper_min_js_descarga.sql
@@application/shared_components/files/assets_js_theme_js_descarga.sql
@@application/shared_components/files/assets_js_tweenmax_min_js_descarga.sql
@@application/shared_components/files/assets_js_typed_2_0_11_js_descarga.sql
@@application/shared_components/files/assets_js_vegas_min_js_descarga.sql
@@application/shared_components/files/assets_js_waypoints_min_js_descarga.sql
@@application/shared_components/files/assets_js_wow_js_descarga.sql
@@application/shared_components/files/cover_jpg.sql
@@application/shared_components/files/assets_js_pdf_mjs.sql
@@application/shared_components/files/assets_js_pdf_worker_mjs.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/fsp_language_preference.sql
@@application/shared_components/logic/application_computations/fsp_language_preference.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/gkasto.sql
@@application/shared_components/user_interface/templates/page/gkasto2.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/region/gkastocarrusel.sql
@@application/shared_components/user_interface/templates/region/latests_news.sql
@@application/shared_components/user_interface/templates/region/latest_news_eng.sql
@@application/shared_components/user_interface/templates/region/latests_news_002.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/theme_display_points.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/security/authentications/application_express_authentication.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
