prompt --application/pages/page_00011
begin
--   Manifest
--     PAGE: 00011
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>1829437844690909
,p_default_application_id=>102
,p_default_id_offset=>0
,p_default_owner=>'XXPOKASTO'
);
wwv_flow_api.create_page(
 p_id=>11
,p_user_interface_id=>wwv_flow_api.id(1954772723207063)
,p_name=>'Noticias'
,p_step_title=>'Noticias'
,p_autocomplete_on_off=>'OFF'
,p_step_template=>wwv_flow_api.id(1968417659227077)
,p_page_template_options=>'#DEFAULT#'
,p_page_is_public_y_n=>'Y'
,p_last_updated_by=>'ADMINPOGK'
,p_last_upd_yyyymmddhh24miss=>'20251218094622'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1974134129258641)
,p_plug_name=>'Carrusel'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'        <section class="page-header" style="background-image: url(#APP_IMAGES#assets/images/Noticias.jpg);">',
'            <div style="text-align: center; position: relative;">',
'                <h2>Noticias</h2>',
'                <ul class="thm-breadcrumb list-unstyled button-right">',
'                    <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:1:&SESSION.">Inicio</a></li>',
'                    <li><span>Noticias</span></li>',
'                </ul>',
'            </div>',
'        </section>',
'    '))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1974283776258642)
,p_plug_name=>'blog-one news'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<section class="blog-one news">',
'  <div class="container">',
'    <div class="row">',
'        <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_22_img_header.png"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>07 Nov 2025</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:44:&SESSION."',
'                  >Colaboradores participan en jornada de voluntariado para el cuidado de los bosques</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Con el objetivo de reforzar la cultura de la prevenci\00F3n y el'),
unistr('                  bienestar laboral, Grupo Kasto llev\00F3 a cabo la Semana de la'),
'                  Seguridad en todas sus divisiones.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:44:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_21_img_header.png"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>02 May 2025</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:43:&SESSION."',
unistr('                  >Celebrando con \00E9xito la Semana de la Seguridad 2025</a'),
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Con el objetivo de reforzar la cultura de la prevenci\00F3n y el'),
unistr('                  bienestar laboral, Grupo Kasto llev\00F3 a cabo la Semana de la'),
'                  Seguridad en todas sus divisiones.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:43:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_20_img_header.png"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>29 Abr 2025</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:42:&SESSION."',
'                  >Simulacro Nacional en Molino Planta Central: Reforzando',
unistr('                  nuestra cultura de prevenci\00F3n</a'),
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
'                  Asi se llevo a cabo el Primer Simulacro Nacional en nuestras',
'                  instalaciones de Molino Planta Central.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:42:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_19_img_header.png"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>24 Feb 2025</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:41:&SESSION."',
unistr('                  >Expo Agr\00EDcola GK: Promoviendo la Agricultura Sustentable</a'),
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  La Expo Agr\00EDcola GK es un evento anual que se lleva a cabo en'),
'                  las instalaciones de Agroindustrias La Barca, en el municipio',
unistr('                  de La Barca, Jalisco, M\00E9xico, desde el 2023, donde se re\00FAnen'),
unistr('                  Empresas l\00EDderes en el Sector Agr\00EDcola con agricultores de la'),
unistr('                  Regi\00F3n.'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:41:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_18_img_header.png"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>24 Ene 2025</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:40:&SESSION."',
'                  >GKM Planta Central Refuerza su Compromiso con la',
'                  Responsabilidad Social Corporativa</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  En el mes de enero, GKM Planta Central llev\00F3 a cabo una'),
unistr('                  capacitaci\00F3n fundamental para su equipo de brigadistas 2025,'),
unistr('                  con el objetivo de fortalecer la preparaci\00F3n ante emergencias'),
'                  y afianzar su compromiso con la seguridad y el bienestar de',
unistr('                  sus colaboradores, as\00ED como con la comunidad en general.'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:40:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_17_img_header.jpg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>02 Dic 2024</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:39:&SESSION."',
'                  >Molino Planta Guadalajara se certifica como Entorno Laboral',
'                  Saludable y Seguro</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  As\00ED se llevo a cabo el cierre de nuestro programa entorno'),
unistr('                  saludable, autoridades sanitarias de la Secretar\00EDa de Salud'),
unistr('                  Jalisco, develaron la placa de certificaci\00F3n mediante la cual,'),
'                  se reconoce a Grupo Kasto Molinos: Planta Guadalajara como',
'                  Entorno Laboral Saludable y Seguro (ENLASSE).',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:39:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_16_img_header.webp"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>15 Nov 2024</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:38:&SESSION."',
unistr('                  >Agroindustrias La Barca Fomenta la Tradici\00F3n del D\00EDa de'),
'                  Muertos con Actividad Familiar</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  En conmemoraci\00F3n por el D\00EDa de Muertos, el equipo de'),
unistr('                  Agroindustrias La Barca, por segundo a\00F1o consecutivo, realiz\00F3'),
'                  una actividad muy especial para los colaboradores y sus',
'                  familiares.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:38:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_15_img_header.jpeg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>06 Oct 2024</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:37:&SESSION."',
unistr('                  >Grupo Kasto Promueve la Concientizaci\00F3n contra el C\00E1ncer de'),
'                  mama</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
'                  El departamento de Recursos Humanos y Seguridad Laboral de',
unistr('                  Grupo Kasto, en sus diferentes divisiones, busc\00F3 a trav\00E9s de'),
unistr('                  diferentes actividades, incentivar la prevenci\00F3n y brindar'),
unistr('                  informaci\00F3n a los colaboradores sobre el c\00E1ncer de mama.'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:37:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_14_img_header.jpeg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>18 Sep 2024</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:36:&SESSION."',
'                  >Materializando Nuestro Modelo de Sostenibilidad</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Para este \00FAltimo trimestre del a\00F1o, nos sentimos muy'),
'                  entusiasmados porque dentro del desarrollo de nuestro programa',
unistr('                  \201CGrupo Kasto rumbo a la Sostenibilidad\201D trabajando en la'),
unistr('                  materialidad para dise\00F1ar nuestro modelo de sostenibilidad.'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:36:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_13_img_header.jpg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>21 Ago 2024</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:35:&SESSION."',
unistr('                  >Grupo Kasto Regresa a la feria m\00E1s importante del Pan:'),
'                  MEXIPAN 2024</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  El pasado 31 de julio di\00F3 inicio Mexipan, la feria m\00E1s'),
'                  importante de la industria panificadora, en la cual se tuvo',
unistr('                  participaci\00F3n con Grupo Kasto Molinos & Ohlala! Boulangerie'),
'                  Bistro.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:35:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#news_12_img_header.jpg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>05 Ago 2024</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:34:&SESSION."',
'                  >Grupo Kasto Rumbo a la Sostenibilidad</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  El programa \201CGrupo Kasto Rumbo a la Sostenibilidad\201D busca'),
'                  capacitar a nuestro personal en temas sobre la Cultura de la',
unistr('                  legalidad, Integridad, Derechos humanos y \00C9tica, etc.'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:34:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#News_11_img_header.jpeg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>20 Jun 2024</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:33:&SESSION."',
'                  >Team Building Trasciende</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Los d\00EDas 19 y 20 de abril, se tuvo el evento anual de'),
unistr('                  Trasciende, evento en el cual se re\00FAnen algunos de los l\00EDderes'),
'                  y talentos de Grupo Kasto.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:33:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#News_10_img_header.jpeg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>25 Jul 2023</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:32:&SESSION."',
'                  >Semana de la Seguridad en Grupo Kasto</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  La semana del 24 al 29 de abril se celebr\00F3 la Semana de la'),
'                  Seguridad en el grupo.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:32:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#Noticia-9.png"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>20 Ene 2022</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:29:&SESSION."',
unistr('                  >Un d\00EDa para donar</a'),
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
'                  En Grupo Kasto Molinos, Colaboramos con Blooders.org en una',
unistr('                  campa\00F1a con el fin de ayudar a muchas personas que necesitan'),
'                  sangre o alguno de sus derivados.',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:29:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="https://apex.oracle.com/pls/apex/gkasto/r/74688/files/static/v27/ohlala_nvo_cpto_e.jpg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>9 Dic 2021</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:31:&SESSION."',
unistr('                  >\201COhlala! Boulangerie Caf\00E9\201D, el nuevo concepto de Ohlala! abre'),
'                  sus puertas.</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Ohlala! Boulangerie Bistrot, inaugur\00F3 con \00E9xito su nuevo'),
unistr('                  concepto de Boulangerie Caf\00E9...'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:31:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#Molino_concepcion.jpeg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>23 Sep 2021</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:30:&SESSION."',
unistr('                  >En Grupo Kasto Molinos estamos: \00A1Construyendo nuestro'),
'                  futuro!</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Grupo Kasto Molinos inaugur\00F3 una nueva planta denominada'),
unistr('                  "Molino La Concepci\00F3n"...'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:30:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#Nueva_sucursal_ohlala.jpeg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>10 Jun 2021</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:27:&SESSION."',
'                  >Ohlala crece y abre una nueva sucursal</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Ohlala contin\00FAa expandi\00E9ndose, inaugurando su octava sucursal'),
unistr('                  en la ciudad de Guadalajara. \00A1Ahora m\00E1s cerca de ti!'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:27:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#Portalgkm_new.jpg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>05 Abr 2021</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:26:&SESSION."',
'                  >Nuevo sitio web de Grupo Kasto Molinos</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
'                  Hoy nos complace anunciar el lanzamiento del nuevo sitio web',
unistr('                  de Grupo Kasto Molinos en su direcci\00F3n habitual'),
'                  www.molinosgrupokasto.com',
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:26:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#Red-Sun-Farms-new.jpg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>18 Feb 2021</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:25:&SESSION."',
'                >',
'                  Red Sun Farms crece e introduce un nuevo logotipo</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  La fuerte demanda de alimentos saludables deber\00EDa elevar la'),
unistr('                  producci\00F3n en los pr\00F3ximos a\00F1os para Red Sun Farms'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:25:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#imagen-15t.png"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>04 Dic 2020</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:22:&SESSION."',
'                >',
'                  Nuevo sitio web</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
'                  Hoy nos complace anunciar el lanzamiento de nuestro nuevo',
unistr('                  sitio web en su direcci\00F3n habitual www.grupokasto.com, con una'),
unistr('                  imagen renovada, m\00E1s din\00E1mica y visual.'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:22:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'      <div class="col-xl-4 col-lg-4">',
'        <div class="blog_one_single mb-30">',
'          <div class="blog_one_image">',
'            <div class="blog_image">',
'              <img',
'                src="#APP_IMAGES#imagen-25.jpg"',
'                alt="Blog One Image"',
'                style="height: 247px; width: 370px"',
'              />',
'              <div class="blog_one_date_box">',
'                <p>09 Jul 2020</p>',
'              </div>',
'            </div>',
'            <div class="blog-one__content" style="padding: 0">',
'              <h3>',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:12:&SESSION."',
'                  >Ciudad del Sol estrena <br />contenedores</a',
'                >',
'              </h3>',
'              <div class="blog_one_text">',
'                <p>',
unistr('                  Los dep\00F3sitos de basura colocados son nuevos pues se cont\00F3 con'),
unistr('                  el apoyo de las empresas como Grupo Kasto y Agr\00EDcola El Rosal.'),
'                </p>',
'              </div>',
'              <div class="read_more_btn">',
'                <a',
'                  href="https://www.grupokasto.com/ords/PDB1/f?p=102:12:&SESSION."',
unistr('                  ><i class="fa fa-angle-right"></i>Leer m\00E1s...</a'),
'                >',
'              </div>',
'            </div>',
'          </div>',
'        </div>',
'      </div>',
'    </div>',
'  </div>',
'</section>',
''))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.component_end;
end;
/
