prompt --application/pages/page_00008
begin
--   Manifest
--     PAGE: 00008
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>1829437844690909
,p_default_application_id=>102
,p_default_id_offset=>0
,p_default_owner=>'XXPOKASTO'
);
wwv_flow_api.create_page(
 p_id=>8
,p_user_interface_id=>wwv_flow_api.id(1954772723207063)
,p_name=>'Molino-de-Trigo'
,p_alias=>'MOLINO-DE-TRIGO'
,p_step_title=>'Molino-de-Trigo'
,p_autocomplete_on_off=>'OFF'
,p_step_template=>wwv_flow_api.id(1968417659227077)
,p_page_template_options=>'#DEFAULT#'
,p_page_is_public_y_n=>'Y'
,p_last_updated_by=>'ADMINPOGK'
,p_last_upd_yyyymmddhh24miss=>'20240727102700'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1973044711258630)
,p_plug_name=>'page-header'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  <section class="page-header" style="background-image: url(#APP_IMAGES#assets/images/Molinos_de_Trigo.jpg); style="width: 1343px;"">',
'            <div  style="text-align: center; position: relative;">',
'                <h2>Molinos de Trigo</h2>',
'                <ul class="thm-breadcrumb list-unstyled button-right">',
'                    <li><a href="https://www.grupokasto.com/ords/PDB1/f?p=102:1:&SESSION.">Inicio</a></li>',
'                    <li><span>Molinos de Trigo</span></li>',
'                </ul>',
'            </div>',
'  </section>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1973387005258633)
,p_plug_name=>'project_detail'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<section class="project_detail">',
'    <div class="container">',
'        <div class="row">',
'            <div class="col-xl-12 col-lg-12 col-md-12">',
'                <div class="project_detail_image">',
'                    <img src="https://molinosgrupokasto.com/PortalGK/assets/images/Div_Molinos_Header2.jpg">',
'                    <!-- <img src="#APP_IMAGES#assets/images/DG_info2.jpg"> -->',
'                </div>',
'            </div>',
'        </div>',
'        <div class="row">',
'            <div class="col-xl-8 col-lg-7">',
'                <div class="project_detail_left_content">',
'                    <div class="harvest_innovations_detail">',
unistr('                        <h2>Divisi\00F3n Molinos</h2>'),
unistr('                        <p>Est\00E1 integrada por diferentes empresas localizadas en el estado de Jalisco. Produce harinas y subproductos de trigo con los m\00E1s altos est\00E1ndares de calidad e inocuidad, satisfaciendo las necesidades de sus clientes. </p>'),
'',
unistr('                        <p>Los molinos est\00E1n estrat\00E9gicamente ubicados en zonas que permiten garantizar el oportuno abastecimiento de trigos  nacionales e importados, as\00ED como la distribuci\00F3n de harinas de trigo y subproductos, a m\00E1s de 10 estados en')
||unistr(' el centro, occidente y norte del pa\00EDs.</p>'),
'                    </div>',
'                    <br>',
'                    <div style="margin-bottom: 20px;">',
'                    <div class="block-title text-left">',
unistr('                        <p>\00BFQUI\00C9NES PARTICIPAN  EN LA DIVISI\00D3N?</p>'),
'                        <h3>UNIDADES DE NEGOCIO </h3>',
'                        <div class="leaf" style="margin-top: 15px;">',
'                            <img src="#APP_IMAGES#assets/images/resources/leaf.png" alt="">',
'                            <!--<img src="#APP_IMAGES#assets/images/resources/leaf.png" alt="">-->',
'                        </div>',
'                    </div>',
'                    <ul class="why_choose_list list-unstyled">',
'                        <li>',
'                            <div class="choose_count">',
'                                <h2>01</h2>',
'                            </div>',
'                            <div class="choose_text">',
'                                <p style="padding-top: 15px;">Grupo Kasto Molinos - Planta Central </p>',
'                            </div>',
'                        </li>',
'                        <li>',
'                            <div class="choose_count">',
'                                <h2>02</h2>',
'                            </div>',
'                            <div class="choose_text">',
'                                <p  style="padding-top: 15px;">Grupo Kasto Molinos - Planta Guadalajara</p>',
'                            </div>',
'                        </li>',
'                        <li>',
'                            <div class="choose_count">',
'                                <h2>03</h2>',
'                            </div>',
'                            <div class="choose_text">',
unistr('                                <p  style="padding-top: 15px;">Grupo Kasto Molinos - Molino La Concepci\00F3n</p>'),
'                            </div>',
'                        </li>',
'                        <!-- <li>',
'                            <div class="choose_count">',
'                                <h2>03</h2>',
'                            </div>',
'                            <div class="choose_text">',
'                                <p  style="padding-top: 15px;">Grupo Kasto Molinos - Planta Jiquilpan</p>',
'                            </div>',
'                        </li> -->',
'                        <li>',
'                            <div class="choose_count">',
'                                <h2>04</h2>',
'                            </div>',
'                            <div class="choose_text">',
unistr('                                <p  style="padding-top: 15px;">Harinera de Atotonilco (Participaci\00F3n accionaria)</p>'),
'                            </div>',
'                        </li>',
'                        <li>',
'                            <div class="choose_count">',
'                                <h2>05</h2>',
'                            </div>',
'                            <div class="choose_text">',
unistr('                                <p  style="padding-top: 15px;">Compa\00F1\00EDa Harinera del Parayas (Participaci\00F3n accionaria)</p>'),
'                            </div>',
'                        </li>',
'                    </ul>',
'                    </div>',
'',
'                    <br>',
'                    <hr>',
'                    <br>',
'',
'                    <div class="project_detail_last_text" style="margin-top: -50px;">',
unistr('                        <p>De estas unidades de negocios se desprenden distintas marcas y variedades de harinas: Harinas de alta prote\00EDna, harinas fuertes, harinas semi-fuertes, harinas suaves, harinas integrales, harinas preparadas, harinas de uso e')
||unistr('special, s\00E9mola de trigo y subproductos de trigo, para satisfacer a los sectores panadero, abarrotero, tortillero, galletero, botanero, pizzas, embutidos, pecuario e industrias con requerimientos especiales.<br> <br>Nos regimos con estrictos procesos')
||unistr(' de calidad y seguridad alimentaria bajo las normas ISO 9001-2015 y HACCP (An\00E1lisis de Peligros y Puntos Cr\00EDticos de Control, por sus siglas en ingl\00E9s).</p>'),
'                    </div>',
'                </div>',
'            </div>',
'            <div class="col-xl-4 col-lg-5">',
'                <div class="project_information_box" style="padding: 40px;">',
'                    <h3>Directorio</h3>',
'                    <ul class="project_information_list list-unstyled" style="padding-bottom: 20px;">',
'                        <li><span> Grupo Kasto Molinos, S.A. de C.V.<br>',
'                            Planta Guadalajara.<br>',
'                        Calle 3 No. 690<br>',
'                        Zona Industrial<br>',
'                        Guadalajara, Jal.&nbsp; C.P. 44940<br>',
'                        Tel: (33) 314 52460, (33) 314 51109</li>',
'',
'                        <ul class="list-unstyled">',
'                            <li><span>Visitanos:</span><a href="https://molinosgrupokasto.com/ords/pdb1/f?p=101:4" style="color: #5b8c51;" target="_BLANK"> molinosgrupokasto.com</a></li>',
'                    </ul>',
'                    <div class="site-footer__social">',
'                            <a href="https://facebook.com/grupokastomolinos" target="_BLANK"><i class="fab fa-facebook-square"></i></a>',
'                            <a href="https://instagram.com/grupokasto" target="_BLANK"><i class="fab fa-instagram"></i></a>',
'                        </div>',
'                    </ul>',
'',
'                    <ul class="project_information_list list-unstyled" style="padding-bottom: 20px;">',
'                        <li><span>Planta Central.<br>',
unistr('                            Av. M\00E9xico No. 3777<br>'),
unistr('                            Col. Condominio M\00E9xico<br>'),
'                            Zapopan, Jal. &nbsp;C.P. 45120<br>',
'                            Tel:(33) 364 78614, (33) 364 78664</li>',
'                    </ul>',
'                    ',
'                    <ul class="project_information_list list-unstyled" style="padding-bottom: 20px;">',
unistr('                        <li><span>Molino La Concepci\00F3n.<br>'),
'                        Km 2.4 Carretera La Barca-Zalamea<br>',
'                        La Barca, Jalisco. &nbsp;C.P. 47910<br>',
'                        Tel: (393) 688 0554, (393) 688 1483<br>',
'                        </li>',
'                    </ul>',
'',
'                    <!-- <ul class="project_information_list list-unstyled" style="padding-bottom: 20px;">',
'                        <li><span>Planta Jiquilpan.<br>',
unistr('                        Av. Pdte. L\00E1zaro C\00E1rdenas No. 251 Norte<br>'),
'                        Jiquilpan, Mich. &nbsp;C.P. 59510<br>',
'                        Tel: (353) 53 30968, (353) 53 30119<br>',
'                        </li>',
'                    </ul> -->',
'                    ',
'                    <ul class="project_information_list list-unstyled" style="padding-bottom: 20px;">',
'                        <li><span>Harinera de Atotonilco, S.A. de C.V.<br>',
'                        Fco. Javier Mina No. 301<br>',
'                        Atotonilco el Alto, Jal. &nbsp;C.P. 47750<br>',
'                        Tel: (391) 91 70001, (391) 91 72305<br>',
'                        </li>',
'',
'                        <ul class="list-unstyled">',
'                            <li><span>Visitanos:</span><a href="https://www.harineradeatotonilco.com.mx/" style="color: #5b8c51;" target="_BLANK"> harineradeatotonilco.com.mx</a></li>',
'                    </ul>',
'                    <div class="site-footer__social">',
'                            <a href="https://www.facebook.com/harineraatotonilco/" target="_BLANK"><i class="fab fa-facebook-square"></i></a>',
'                        </div>',
'                    </ul>',
'                    ',
'                    <ul class="list-unstyled">',
'                        <li><span>Cia. Harinera del Parayas, S.A. de C.V.<br>',
'                        Av. Vallarta No. 3998<br>',
'                        Col. Juan Manuel Vallarta<br>',
'                        Zapopan, Jal.&nbsp; C.P. 45120<br>',
'                        Tel: (33) 31 217100</li>',
'                         <li><span>Visitanos:</span><a href="https://harineradelparayas.com.mx" style="color: #5b8c51;" target="_BLANK"> harineradelparayas.com.mx</a></li>',
'                    </ul>',
'',
'                </div>',
'            </div>',
'        </div>',
'    </div>',
'</section>',
'<br>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1973483949258634)
,p_plug_name=>'recent_project_three'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<section class="recent_project_three">',
'    <div class="container-fullwidth">',
'         <div class="block-title text-center">',
'            <p>Nuestras Instalaciones</p>',
unistr('            <h3>CON\00D3CELAS</h3>'),
'            <div class="leaf">',
'                <img src="#APP_IMAGES#assets/images/resources/leaf.png" alt="">',
'            </div>',
'        </div>',
'        <div class="recent_project_three_carousel owl-theme owl-carousel">',
'',
'            <!--Item-->',
'            <div class="project_three_single" data-wow-delay="1200ms">',
'              <div class="project_three_image">',
'                   <div class="gallery_two_single">',
'                        <div class="gallery_two_image">',
'                            <img src="#APP_IMAGES#assets/images/DM_GDL2.jpg" alt="">',
'                            <div class="gallery_two_hover_box">',
'                                <div class="gallery_two_icon">',
'                                    ',
'                                    <div class="about_two_content">',
'                                        <h2>PLANTA <br> Guadalajara</h2>',
'                                    </div>',
'                                            ',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'          ',
'            <!--Item-->',
'            <div class="project_three_single" data-wow-delay="600ms">',
'                <div class="project_three_image">',
'                   <div class="gallery_two_single">',
'                        <div class="gallery_two_image">',
'                            <img src="#APP_IMAGES#assets/images/DM_C.jpg" alt="">',
'                            <div class="gallery_two_hover_box">',
'                                <div class="gallery_two_icon">',
'                                    ',
'                                    <div class="about_two_content">',
'                                        <h2>PLANTA <br> Central</h2>',
'                                    </div>',
'                                            ',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'',
'            <!--Item-->',
'            <div class="project_three_single" data-wow-delay="1200ms">',
'              <div class="project_three_image">',
'                   <div class="gallery_two_single">',
'                        <div class="gallery_two_image">',
'                            <img src="https://apex.oracle.com/pls/apex/gkasto/r/74688/files/static/v33/Molino_concepcion_about_us.jpeg" alt="">',
'                            <div class="gallery_two_hover_box">',
'                                <div class="gallery_two_icon">',
'                                    ',
'                                    <div class="about_two_content">',
unistr('                                        <h2>Molino <br>La Concepci\00F3n</h2>'),
'                                    </div>         ',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            <!--Item-->',
'',
'            <!--Item-',
'            <div class="project_three_single" data-wow-delay="1200ms">',
'              <div class="project_three_image">',
'                   <div class="gallery_two_single">',
'                        <div class="gallery_two_image">',
'                            <img src="#APP_IMAGES#assets/images/DM_J.jpg" alt="">',
'                            <div class="gallery_two_hover_box">',
'                                <div class="gallery_two_icon">',
'                                    ',
'                                    <div class="about_two_content">',
'                                        <h2>PLANTA <br>Jiquilpan</h2>',
'                                    </div>         ',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            --Item-->',
'            <div class="project_three_single" data-wow-delay="900ms">',
'              <div class="project_three_image">',
'                   <div class="gallery_two_single">',
'                        <div class="gallery_two_image">',
'                            <img src="#APP_IMAGES#assets/images/DM_P.jpg" alt="">',
'                            <div class="gallery_two_hover_box">',
'                                <div class="gallery_two_icon">',
'                                    ',
'                                    <div class="about_two_content">',
'                                        <h2>Parayas</h2>',
'                                    </div>',
'                                            ',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            <!--Item-->',
'            <div class="project_three_single" data-wow-delay="900ms">',
'              <div class="project_three_image">',
'                   <div class="gallery_two_single">',
'                        <div class="gallery_two_image">',
'                            <img src="#APP_IMAGES#assets/images/DM_a2.jpg" alt="">',
'                            <div class="gallery_two_hover_box">',
'                                <div class="gallery_two_icon">',
'                                    ',
'                                    <div class="about_two_content">',
'                                        <h2>Atotonilco</h2>',
'                                    </div>',
'                                            ',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'            <!--Item-->',
'            <!-- <div class="project_three_single" data-wow-delay="900ms">',
'              <div class="project_three_image">',
'                   <div class="gallery_two_single">',
'                        <div class="gallery_two_image">',
'                            <img src="#APP_IMAGES#assets/images/DM_GDL1.jpg" alt="">',
'                            <div class="gallery_two_hover_box">',
'                                <div class="gallery_two_icon">',
'                                    ',
'                                    <div class="about_two_content">',
'                                        <h2>PLANTA <br> Guadalajara</h2>',
'                                    </div>',
'                                            ',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div> -->',
'        </div>',
'    </div>',
'</section>',
''))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.component_end;
end;
/
