prompt --application/pages/page_00006
begin
--   Manifest
--     PAGE: 00006
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2020.03.31'
,p_release=>'20.1.0.00.13'
,p_default_workspace_id=>1829437844690909
,p_default_application_id=>102
,p_default_id_offset=>0
,p_default_owner=>'XXPOKASTO'
);
wwv_flow_api.create_page(
 p_id=>6
,p_user_interface_id=>wwv_flow_api.id(1954772723207063)
,p_name=>'Privacidad'
,p_step_title=>'Privacidad'
,p_autocomplete_on_off=>'OFF'
,p_step_template=>wwv_flow_api.id(1968417659227077)
,p_page_template_options=>'#DEFAULT#'
,p_page_is_public_y_n=>'Y'
,p_last_updated_by=>'ADMINPOGK'
,p_last_upd_yyyymmddhh24miss=>'20211117092655'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1972322743258623)
,p_plug_name=>'page-header'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  <section class="page-header" style="background-image: url(#APP_IMAGES#encabezado_1.jpg );">',
'            <div style="text-align: center; position: relative;">',
'                <h2>Avisos de privacidad de las empresas</h2>',
'                <ul class="thm-breadcrumb list-unstyled button-right">',
'                    <li><a href="index.html">Inicio</a></li>',
'                    <li><span>Privacidad</span></li>',
'                </ul>',
'            </div>',
'   </section>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1972403060258624)
,p_plug_name=>'service_detail'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<section class="service_detail" style="padding-bottom: 20px;">',
'            <div class="container">',
'                <div class="row">',
'                    <div class="col-xl-4 col-lg-4">',
'                         <div class="project_information_box">',
'                            ',
'                           ',
'                                ',
unistr('                                <h3>DIVISI\00D3N GRANOS</h3>'),
'                               ',
'                                    <ul class="project_information_list list-unstyled site-directory">',
'                                    <li><p><a id="_semillas" href="#" > Semillas y Fibras Internacionales S.A. de C.V.</a></p></li>',
'                                    <li><p><a id="_ferropuerto" href="#" > Ferropuerto de Sonora S.A. de C.V.</a></p></li>',
'                                    <li><p><a id="_agroindustrias" href="#" > Agroindustrias La Barca S.A. de C.V.</a></p></li>',
'                                    <li><p><a id="_sInsumos" href="#" > Semillas e Insumos GK S.A. de C.V.</a></p></li> <!--Hover aviso de privacidad-->',
'                                    <li><p><a id="_Kasavi" href="#" > Kasavi Comercial S.A. de C.V.</a></p></li>',
'                                    </ul>',
'                                ',
unistr('                                <h3>DIVISI\00D3N MOLINOS</h3>'),
'                                ',
'                                    <ul class="project_information_list list-unstyled site-directory">',
'                                    <!--<li><p><a id="_mcentral" href="#" > Molino Central, S.A. de C. V.</a></p></li>  quitar molino central de cofigo java-->',
'                                    <li><p><a id="_mguadalajara" href="#" > Grupo Kasto Molinos S.A. de C.V.</a></p></li>',
'                                    <!--Empresa Grupo Kasto Molinos S.A. de C.V.-->',
unistr('                                    <!--<li><p><a id="_mrafael" href="#" > Molino de Trigo San Rafael S.A. de C.V.</a></p></li> quitar del c\00F3digo-->'),
'                                    <!--<li><p><a id="_mjiquilpan" href="#" > Molino de Trigo de Jiquilpan S.A. de C.V.</a></p></li>-->',
'                                    <li><p><a id="_hatotonilco" href="#" > Harinera de Atotonilco S.A. de C.V.</a></p></li>',
unistr('                                    <li><p><a id="_hparayas" href="#" > Compa\00F1\00EDa Harinera del Parayas S.A. de C.V.</a></p></li>'),
'                                    </ul>',
'                                ',
unistr('                                <h3>DIVISI\00D3N PECUARIA</h3>'),
'                                ',
'                                    <ul class="project_information_list list-unstyled site-directory">',
'                                    <li><p><a id="_agroalimentos" href="#" > Agrocomercio San Juan S.A. de C.V.</a></p></li><!-- se queda igual-->',
'                                    <li><p><a id="_folap" href="#" > Folap S.A. de C. V.</a></p></li>',
'                                    </ul>',
'',
unistr('                                <h3>DIVISI\00D3N SERVICIOS</h3>'),
'                                ',
'                                    <ul class="project_information_list list-unstyled site-directory">',
'                                    <li><p><a id="_multiservicios" href="#" > Multiservicios Profesionales GK S.A. de C.V.</a></p></li>',
unistr('                                    <li><p><a id="_regional" href="#" > Regional de La Construcci\00F3n S.A. de C.V.</a></p></li>'),
'                                    <li><p><a id="_ciudadsol" href="#" > Servicios Ciudad del Sol S.A. de C.V.</a></p></li>',
'                                    <li><p><a id="_transporte" href="#" > Transportes Kasto S.A. de C.V.</a></p></li>',
unistr('                                    <li><p><a id="_IDGK" href="#" >Investigaci\00F3n y Desarrollo GK S.A de C.V.</a></p></li> <!--misma direcci\00F3n de GK-->'),
'                                    </ul>',
'                                ',
'                                <h3>INVERNADEROS</h3>',
'                               ',
'                                    <ul class="project_information_list list-unstyled site-directory">',
unistr('                                    <li><p><a id="_rosa" href="#" > Agr\00EDcola El Rosal S.A. de C.V.</a></p></li>'),
'                                    </ul>',
'',
'',
unistr('                                <h3>Panaderia y bistr\00F3 </h3>'),
'                                ',
'                                    <ul class="project_information_list list-unstyled site-directory">',
'                                    <li><p><a id="_operadora" href="#" > Operadora Ohlala, S.A. de C.V.</a></p></li>',
'                                    <li><p><a id="_productoraoh" href="#" > Productora de alimentos Oh, S.A. de C.V.</a></p></li>',
'                                    </ul>',
'                                ',
'                                 <h3>PRODUCTOS DE CONSUMO</h3>',
'                                ',
'                                    <ul class="project_information_list list-unstyled site-directory">',
'                                    <li><p><a id="_consumoz" href="#" > Productos de Consumo "Z" S.A. de C.V.</a></p></li>',
'                                    </ul>',
'                                ',
'                                 ',
'                                ',
unistr('                                 <h3>PROMOTORA DE INVERSI\00D3N</h3>'),
'                                ',
'                                    <ul class="list-unstyled site-directory">',
'                                    <li><p><a id="_inmobiliario" href="#" > Desarrollo Inmobiliario Kasto S.A. de C.V.</a></p></li>',
'                                    </ul>',
'                                ',
'                           ',
'                            ',
'                        </div>  ',
'                        <br>',
'                        <div class="service_details_left">',
'                            ',
'                            <div class="need_help_box">',
'                                <h2>Si necesita ayuda</h2>',
unistr('                                <p>Podemos contactarnos con usted. Env\00EDenos un correo electr\00F3nico y un miembro de nuestro equipo lo ayudar\00E1.</p>'),
'                                <h5 style="',
'                                    color: var(--thm-base);',
'                                    font-size: 18px;                                 ',
'                                ">',
'                                <br>',
'                                <div class="site-need-help">',
'                                    <a style="    text-transform:none;" href="mailto:datospersonales@grupokasto.com"><span class="icon-message"></span>datospersonales@grupokasto.com</a>',
'                                </div>',
'',
'                                ',
'',
'',
'',
'                                <!--<a href="mailto:datospersonales@grupokasto.com"><span class="icon-message"></span>datospersonales@grupokasto.com</h5></a> !--Revisar con obed-->',
'                            </div>',
'                            ',
'                        </div>',
'                    </div>',
'                    <div class="col-xl-8 col-lg-8">',
'                        <div class="service_details_right">',
'                         ',
'                            <div class="harvest_innovations">',
'                                <div class="block-title text-left" style="padding: 0; margin: 0;">',
unistr('                                    <p>Tu informaci\00F3n en manos seguras</p>'),
'                                </div>',
'                                <h2>Avisos de privacidad de las empresas</h2>',
unistr('                                <p>En cumplimiento a lo establecido por la Ley Federal de Protecci\00F3n de Datos Personales '),
unistr('                                en Posesi\00F3n de Particulares y su reglamento (en lo sucesivo la \201CLey\201D) y que coadyuvan con '),
'                                nuestro objetivo de proteger sus datos personales, es que:.</p>',
'                                <div>',
'                                    <p id="direccion" class="harvest_innovations_bottom_text">Grupo Kasto, Oficinas Corporativas<br>',
'                                    Av. Padre Hidalgo No. 600<br>',
'                                    Santa Ana Pacueco, Gto.<br>',
'                                    C.P. 36910<br>',
'                                    Tels. (352) 52 6 28 29<br>',
'                                    (352) 52 6 17 70<br>',
'                                    www.grupokasto.com</p>',
'                                </div>',
'                            </div>',
'                         ',
'                            <div class="agriculture_solutions">',
unistr('                                <p>Es responsable de recabar sus datos personales, del tratamiento que se le d\00E9 a los mismos '),
unistr('                                y de su protecci\00F3n y hace de su conocimiento, que los datos personales y/o patrimoniales de '),
unistr('                                personas f\00EDsicas que le son solicitados, ser\00E1n utilizados exclusivamente para la realizaci\00F3n '),
unistr('                                de actividades concernientes a la posible relaci\00F3n comercial, o bien sobre la relaci\00F3n comercial '),
'                                ya existente que sostiene con usted, como:</p>',
'                            </div>',
'                            <ul class="list-unstyled">',
unistr('                                <li><i class="fa fa-check"></i>Participaci\00F3n en el proceso de selecci\00F3n de clientes o proveedores que realizamos.</li>'),
'                                <li><i class="fa fa-check"></i>Mantener nuestra lista de los contactos de clientes y proveedores autorizados.</li>',
unistr('                                <li><i class="fa fa-check"></i>Emisi\00F3n y consulta de referencias comerciales.</li>'),
unistr('                                <li><i class="fa fa-check"></i>Llevar un registro y cotizaci\00F3n de los de bienes y/o servicios cuyo suministro'),
'                                otorgamos o requerimos.</li>',
unistr('                                <li><i class="fa fa-check"></i>Cumplimiento de nuestras pol\00EDticas o procedimientos internos respecto a clientes y '),
unistr('                                proveedores, as\00ED como informarle de cambios al respecto.</li>'),
unistr('                                <li><i class="fa fa-check"></i>Atenci\00F3n de dudas y sugerencias.</li>'),
unistr('                                <li><i class="fa fa-check"></i>Cobro o pago de contraprestaciones y facturaci\00F3n.</li>'),
unistr('                                <li><i class="fa fa-check"></i>Elaboraci\00F3n de contratos y/u \00F3rdenes de compra.</li>'),
unistr('                                <li><i class="fa fa-check"></i>Actualizaci\00F3n de bases de datos.</li>'),
unistr('                                <li><i class="fa fa-check"></i>Mantener una comunicaci\00F3n que nos permita evaluar la calidad de los bienes y/o '),
'                                servicios que otorgamos o requerimos.</li>',
'                                <li><i class="fa fa-check"></i>Invitaciones a eventos sociales que organicemos.</li>',
'                            </ul>',
unistr('                            <p class="service_details_last_text">En forma accesoria los datos personales podr\00E1n ser utilizados con fines '),
unistr('                            mercadot\00E9cnicos, publicidad, prospecci\00F3n comercial, as\00ED como para la elaboraci\00F3n de perfil de clientes para '),
unistr('                            el desarrollo y ofrecimiento de nuevos productos, realizaci\00F3n de encuestas, creaci\00F3n o implementaci\00F3n de '),
unistr('                            procesos anal\00EDticos y estad\00EDsticos necesarios o convenientes relacionados con los bienes y/o servicios cuyo '),
'                            suministro otorgamos o requerimos.</p>',
'                            <div class="accrodion-grp" data-grp-name="faq-one-accrodion">',
'                                <div class="accrodion active">',
'                                    <div class="accrodion-title">',
'                                        <h4>Solicitud de Datos</h4>',
'                                    </div>',
'                                    <div class="accrodion-content">',
'                                        <div class="inner">',
'                                            <p>Para las finalidades antes mencionadas y dependiendo del tipo de contrato, bien, servicio o monto de',
unistr('                                            los mismos, es que pudi\00E9ramos requerir entre otros los siguientes datos de identificaci\00F3n personales o '),
unistr('                                            de la empresa que representa (incluyendo los derivados de sus caracter\00EDsticas f\00EDsicas): nombre, domicilio,'),
unistr('                                            tel\00E9fonos, correos electr\00F3nicos, estudios acad\00E9micos, historial crediticio, afiliaciones, edad, estado '),
'                                            civil, apoderados legales, poderes, acta constitutiva, comprobante de domicilio del negocio (recibo de ',
unistr('                                            luz, tel\00E9fono, agua o cable), comprobante de domicilio particular del apoderado, CURP, copia de la '),
unistr('                                            identificaci\00F3n oficial del apoderado y las firmas autorizadas, forma oficial R1 y c\00E9dula del RFC en copia'),
'                                            simple, o en su caso, declaraciones anuales de ISR y IETU debidamente presentadas, contrato de ',
'                                            arrendamiento en el caso de no ser propio el local.',
'                                            <br> Se realiza el tratamiento de los datos solicitados anteriormente (datos personales y/o patrimoniales,',
unistr('                                            de clientes, proveedores y contacto de \00E9stos) de conformidad con los principios de licitud, '),
unistr('                                            consentimiento, informaci\00F3n, calidad, finalidad, lealtad, proporcionalidad y responsabilidad en t\00E9rminos '),
'                                            de lo dispuesto en la Ley.</p>',
'                                        </div><!-- /.inner -->',
'                                    </div>',
'                                </div>',
'                                <div class="accrodion ">',
'                                    <div class="accrodion-title">',
unistr('                                        <h4>Protecci\00F3n de la Informaci\00F3n</h4>'),
'                                    </div>',
'                                    <div class="accrodion-content">',
'                                        <div class="inner">',
unistr('                                            <p>Le informamos que, con la finalidad de impedir el acceso y revelaci\00F3n no autorizada, mantener la '),
unistr('                                            exactitud de los datos y garantizar la utilizaci\00F3n correcta de la informaci\00F3n, aplicamos los '),
unistr('                                            procedimientos f\00EDsicos, tecnol\00F3gicos y administrativos apropiados para proteger la informaci\00F3n que'),
unistr('                                            recabamos. La informaci\00F3n personal y patrimonial que nos proporciona, de conformidad con la Legislaci\00F3n, '),
'                                            se guarda en bases de datos controladas y con acceso limitado.</p>',
'                                        </div><!-- /.inner -->',
'                                    </div>',
'                                </div>',
'                                <div class="accrodion">',
'                                    <div class="accrodion-title">',
'                                        <h4>Derecho de Acceso</h4>',
'                                    </div>',
'                                    <div class="accrodion-content">',
'                                        <div class="inner">',
unistr('                                            <p>Se le informa que podr\00E1 ejercer sus derechos de Acceso, Rectificaci\00F3n, Cancelaci\00F3n y Oposici\00F3n (ARCO)'),
unistr('                                            de sus datos y que nos proporcion\00F3, siempre y cuando su relaci\00F3n comercial con nosotros est\00E1 saldada, a '),
unistr('                                            trav\00E9s del formulario que podr\00E1 obtenerse mediante solicitud a la siguiente direcci\00F3n electr\00F3nica: '),
unistr('                                            datospersonales@grupokasto.com as\00ED como en el domicilio y tel\00E9fono se\00F1alado al inicio del presente '),
'                                            aviso.</p>',
'                                        </div><!-- /.inner -->',
'                                    </div>',
'                                </div>',
'                                <div class="accrodion">',
'                                    <div class="accrodion-title">',
'                                        <h4>Transferencia de Datos</h4>',
'                                    </div>',
'                                    <div class="accrodion-content">',
'                                        <div class="inner">',
'                                            <p>Asimismo le informamos que sus datos personales pueden ser transferidos y tratados dentro de nuestra ',
unistr('                                            empresa y de terceras personas ya sean f\00EDsicas o morales que de alguna manera existe una relaci\00F3n de '),
unistr('                                            cliente, proveedur\00EDa o de cualquier otra cosa.'),
unistr('                                            <br>En este sentido, su informaci\00F3n puede ser, para que estas empresas adquieran o le vendan bienes '),
'                                            y/o servicios cuyo suministro otorgamos o requerimos.<br>',
unistr('                                            <br>Cualquier modificaci\00F3n a este aviso de privacidad podr\00E1 consultarla en www.grupokasto.com Nos '),
'                                            reservamos el derecho de efectuar en cualquier momento modificaciones o actualizaciones al presente ',
unistr('                                            aviso de privacidad para la prestaci\00F3n u ofrecimiento de nuestros bienes y/o servicios, para la atenci\00F3n '),
unistr('                                            de modificaciones legislativas, regulatorias o jurisprudenciales, pol\00EDticas internas, pr\00E1cticas del '),
unistr('                                            mercado o por cualquier otra raz\00F3n. Cualquier cambio que se realice a este aviso de privacidad, ser\00E1'),
unistr('                                            incorporado al mismo y ser\00E1 dado a conocer en alguno de los siguientes medios: (i) anuncios visibles en '),
unistr('                                            nuestros establecimientos o centros de atenci\00F3n a clientes; o (ii) tr\00EDpticos o folletos disponibles en '),
unistr('                                            nuestros establecimientos o centros de atenci\00F3n a clientes; o (iii) nuestra p\00E1gina de internet '),
'                                            www.grupokasto.com</p>',
'                                        </div><!-- /.inner -->',
'                                    </div>',
'                                </div>',
'                            </div>',
'                        </div>',
'                    </div>',
'                </div>',
'            </div>',
'        </section>',
''))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(1972596110258625)
,p_plug_name=>'js'
,p_region_template_options=>'#DEFAULT#:margin-bottom-none:t-Form--noPadding'
,p_plug_template=>wwv_flow_api.id(1990753307084041)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<script type="text/javascript">',
'    ',
'    var type = new Array();',
'    var content = new Array();',
'',
'    type[0] = "_semillas";',
'    type[1] = "_ferropuerto";',
'    type[2] = "_agroindustrias";',
'    type[3] = "_sInsumos";',
'    type[4] = "_Kasavi";',
'',
'    ',
'    /*type[3] = "_mcentral";*/',
'    type[5] = "_mguadalajara";',
'    /*type[5] = "_mrafael";',
'    type[6] = "_mjiquilpan";*/',
'    type[6] = "_hatotonilco";',
'    type[7] = "_hparayas";',
'    ',
'    type[8] = "_agroalimentos";',
'    type[9] = "_folap";',
'    ',
'    type[10] = "_rosa";',
'    ',
'    type[11] = "_consumoz";',
'    ',
'    type[12] = "_multiservicios";',
'    type[13] = "_regional";',
'    type[14] = "_ciudadsol";',
'    type[15] = "_transporte";',
'    type[16] = "_IDGK";',
'    ',
'    type[17] = "_inmobiliario";',
'',
'    type[18] = "_operadora";',
'    type[19] = "_productoraoh";',
'',
'',
unistr('    content[0] = "Semillas y Fibras Internacionales, S.A. de C.V.<br>Circuito Interior No. 1003<br>Parque Industrial<br>Ciudad Obreg\00F3n, Son.<br>C.P. 85065<br>Tels. (644) 41 10150<br>(644) 41 10018<br>www.grupokasto.com";'),
unistr('    content[1] = "Ferropuerto de Sonora, S.A. de C. V.<br>Carr. Internacional Km. 545-5<br>Zona Industrial<br>Ciudad Obreg\00F3n, Son.<br>C.P. 85090<br>Tels. (644) 41 10435<br>(644) 41 10786<br>";'),
'    content[2] = "Agroindustrias La Barca, S.A. de C. V.<br>Km. 2.5 Carr. La Barca-Zalamea<br>Zona Industrial<br>La Barca, Jal.<br>C.P. 47910<br>Tels. (393) 93 53224<br>(393) 93 50504<br>www.grupokasto.com";',
'    content[3] = "Semillas e Insumos GK S.A. de C.V.<br>Av. Padre Hidalgo No. 600<br>Santa Ana Pacueco, Gto.<br>C.P. 36910<br>Tel. (352) 52 62324<br>www.grupokasto.com";',
'    content[4] = "Kasavi Comercial S.A. de C.V.<br>Av. Padre Hidalgo No. 410-5<br>Santa Ana Pacueco, Gto.<br>C.P. 36910<br>Tel 352 526 1766<br>";',
'',
'    ',
unistr('    content[5] = "Empresa: Grupo Kasto Molinos S.A. de C.V.<br>Domicilio: Av. M\00E9xico No. 3777<br>Colonia: Condominio M\00E9xico<br>Municipio: Zapopan Estado: Jalisco<br>C.P.: 45120 Tel\00E9fono: (33) 36478614<br>M\00E9xico<br>www.grupokasto.com";'),
unistr('    content[6] = "Empresa: HARINERA DE ATOTONILCO, S.A. DE C.V.<br>Domicilio: Feo. Javier Mina No. 301<br>Colonia: Centro<br>Municipio: Atotonilco El Alto Estado: Jalisco<br>C.P. 47750<br>Tel\00E9fono: (391) 91 70001<br>M\00E9xico<br>www.grupokasto.com";'),
unistr('    content[7] = "Empresa: CIA. HARINERA DEL PARAYAS, S.A. DE C.V.<br>Domicilio: Av. Vallarta No. 3998<br>Colonia: Col. Juan Manuel Vallarta Municipio: Zapopan<br>Estado: Jalisco<br>C.P. 45120 Tel\00E9fono: (33) 31 217100 M\00E9xico<br>www.grupokasto.com";'),
'',
'    content[8] = "Agrocomercio San Juan S.A. de C.V.<br>Av. Padre Hidalgo 410-6<br>Centro<br>Santa Ana Pacueco, Gto.<br>C.P. 36910<br>Tel. (352) 52 60705<br>www.grupokasto.com";',
unistr('    content[9] = "Empresa: Folap, S.A. de C.V.<br>Domicilio: Blvd. L\00E1zaro C\00E1rdenas No. 1109<br>Colonia: Santa Fe<br>Municipio: La Piedad<br>Estado: Michoac\00E1n<br>C.P. 59370<br>Tel\00E9fono: (352) 52 21350<br>M\00E9xico<br>www.grupokasto.com";'),
'    ',
unistr('    content[10] = "Agr\00EDcola El Rosal, S.A. de C. V.<br>Granja Santa Elena<br>Rancho Altamira<br>Numar\00E1n, Mich.<br>C.P. 59430<br>Tels. (352) 52 29585<br>(352) 52 25106<br>www.grupokasto.com";'),
'',
unistr('    content[11] = "Productos de Consumo \201CZ\201D<br>Incalpa No. 2000, Perif\00E9rico Sur<br>Las Pintas<br>Tlaquepaque, Jal.<br>C.P. 45590<br>Tels. (33) 39 151500<br>(33) 39 151513.<br>www.grupokasto.com";'),
'',
'    content[12] = "Multiservicios Profesionales GK, S.A. de C. V.<br>Av. Padre Hidalgo 410-1<br>Centro<br>Santa Ana Pacueco, Gto.<br>C.P. 36910<br>Tel. (352) 52 61939<br>www.grupokasto.com";',
unistr('    content[13] = "Regional de La Construcci\00F3n, S.A. de C. V.<br>Blvd. L\00E1zaro C\00E1rdenas No. 1111<br>Col. Santa Fe<br>La Piedad, Mich.<br>C.P. 59370<br>Tels. (352) 52 61350<br>(352) 52 61050<br>www.grupokasto.com";'),
unistr('    content[14] = "Servicios Ciudad del Sol, S.A. de C. V.<br>Av. Michoac\00E1n No. 475<br>Col. Ciudad del Sol<br>La Piedad, Mich.<br>C.P. 59310<br>Tel. (352) 52 66269<br>www.grupokasto.com";'),
'    content[15] = "Transportes Kasto, S.A. de C. V.<br>Av. Padre Hidalgo No. 410-4<br>Centro<br>Santa Ana Pacueco, Gto.<br>C.P. 36910<br>Tels. (352) 52 61340<br>(352) 52 25571<br>www.grupokasto.com";',
unistr('    content[16] = "Empresa: Investigaci\00F3n y Desarrollo GK S.A de C.V<br>Domicilio: Av. Abedules 414<br>Colonia: Rinconada Santa Rita<br>Municipio: Zapopan Estado: Jalisco<br>C.P. 45120 Tel\00E9fono: (33) 38 13 4281<br>M\00E9xico<br>www.grupokasto.com";'),
'',
'    content[17] = "Desarrollo Inmobiliario Kasto, S.A. de C.V.<br>Av. Padre Hidalgo No. 410-2<br>Centro<br>Santa Ana Pacueco, Gto.<br>C.P. 36910<br>Tels. (352) 52 61939<br>(352) 52 60705<br>www.grupokasto.com";',
'',
unistr('    content[18] = "Operadora Ohlala <br>Domicilio: Av. Sebasti\00E1n Bach 5074<br>Col. La Estancia<br>Zapopan, Jal.&nbsp; C.P. 45020 <br>Tel: 3315 62 6995<br>M\00E9xico<br>https://ohlala.com.mx/";'),
'',
'',
unistr('    content[19] = "Productora de alimentos Oh, S.A. de C.V.<br>Domicilio: Anillo Perif. Nte. Manuel G\00F3mez Morin 6650 Bodega 1<br>Col. Miramar<br>Zapopan, Jal.&nbsp; C.P. 45060 <br>Tel: 333040909<br>M\00E9xico<br>https://ohlala.com.mx/";'),
'    ',
'',
'    var list = [];',
'',
'    //guardas los datos',
'    for (var i = 0; i < type.length; i++) {',
'',
'        list.push({',
'        "type": type[i],',
'        "content": content[i]',
'      });',
'    };',
'',
'    json = JSON.stringify(list); // aqui tienes la lista de objetos en Json',
'    var init = JSON.parse(json); //Parsea el Json al objeto anterior.',
'',
'',
'    ',
'    ',
'        window.onclick = function (e) {',
'        if (e.target.localName == ''a'') {',
'            console.log(e.target.id);',
'            var type = e.target.id;',
'            ',
'           for(var i = 0; i < init.length; i++) {',
'            var obj = init[i];',
'                if(type==obj.type){',
'                    console.log(obj);',
'                    $("#direccion").text("");',
'                    $("#direccion").append(obj.content);',
'                }',
'            ',
'            }',
'           ',
'        }',
'    }',
'    ',
'    ',
'</script>'))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.component_end;
end;
/
